server:
  port: 8083
spring:
  application:
    name: piggy-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:luyuhs123/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
          username: luyuhs123
          passphrase: LUYUSHcueite1025
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka